# Generated by Django 3.1.5 on 2021-02-09 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210209_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='total_working_dats',
            new_name='total_working_days',
        ),
        migrations.RenameField(
            model_name='historicalemployee',
            old_name='total_working_dats',
            new_name='total_working_days',
        ),
        migrations.AlterField(
            model_name='department',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 10, 55, 32, 191722)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 10, 55, 32, 191988)),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 10, 55, 32, 191988)),
        ),
    ]
